name: Test & Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Obtain the source code
      - uses: actions/checkout@v2

      # Push to GCP
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ddns
          runtime: go113
          entry_point: HandleDDNSUpdate
          region: europe-west2
          credentials: ${{ secrets.GCP_DEPLOY_KEY }}